Set executable flag on src directory because of problem running subprocess
  File "/gcovr/gcovr/formats/gcov/read.py", line 563, in __get_gcov_process
    **kwargs,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/gcovr/gcovr/tests/not_writable_source_dir/src'