tests: update pip before installing dependencies
The Travis/Python-3.4 build failed with an error within pkg_resources,
i.e. setuptools/pip infrastructure:
    AttributeError: _DistInfoDistribution__dep_map
Online sources indicate updating pip first should help.

The problem is that pytest depends on setuptools, and also on other
modules that require up to date setuptools during their installation.
Since their installation order is undefined, installation can fail if
setuptools isn't updated first.