Fix bundle of standalone executable
With Python 3.12 following message occurred if the application is executed:
```
Traceback (most recent call last):
  File "pyinstaller_entrypoint.py", line 22, in <module>
ModuleNotFoundError: No module named 'gcovr.__main__'
[267] Failed to execute script 'pyinstaller_entrypoint' due to unhandled exception!
```