Fix verbose output when using existing gcov files
When gcovr is invoked with `-v` and `-g` switches, it fails with error:
```
    ....
    print('  source_fname '+source_fname)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
This patch disables printing of `source_fname` when `source_fname is None`